; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = omniphone

; ── Main firmware (upload to Teensy 4.0) ─────────────────────────────────────
[env:omniphone]
platform = teensy
board = teensy40
framework = arduino
lib_ldf_mode = chain+

; ── Testing firmwares
[env:raw_sensor_readout]
extends = env:omniphone
build_src_filter = -<*> +<../test/raw_sensor_readout.cpp>

[env:sensor_comparison]
extends = env:omniphone
build_src_filter = -<*> +<../test/sensor_comparison.cpp>

[env:led_test]
extends = env:omniphone
build_src_filter = -<*> +<../test/led_test.cpp>

[env:electrode_relocation]
extends = env:omniphone
build_src_filter = -<*> +<../test/electrode_relocation.cpp>