; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

; ── Main firmware (upload to Teensy 4.0) ─────────────────────────────────────
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
lib_ldf_mode = chain+


[env:raw_sensor_readout] ; hardware troubleshooter
extends = env:teensy40
build_src_filter = +<../test/raw_sensor_readout.cpp> -<main.cpp>