#!/usr/bin/env python3
"""Convert the wavs in variants/teensy40-12pad-screen/samples/ into the C header
the firmware bakes into flash (sample_data.h).

File naming convention:  <name>_<rootHz>.wav   e.g.  hang_146.83.wav
  • <name>   → the C identifier prefix, uppercased (HANG_SAMPLE, HANG_ROOT_HZ …)
  • <rootHz> → the pitch of the recording, so the engines know how to transpose.

The firmware expects a `hang_*.wav` (Grain Hang mode) and a `strings_*.wav`
(Strings mode). To swap a sound: drop in your replacement wav (mono or stereo,
any common rate — best 44100 Hz mono, a few seconds max), keep the naming
convention, run this script, rebuild + upload. ~1.9 MB of flash is free; keep
the total well under that."""
import os, re, struct, sys, wave

HERE = os.path.dirname(__file__)
SAMPLES = os.path.join(HERE, "..", "variants", "teensy40-12pad-screen", "samples")
OUT = os.path.join(HERE, "..", "variants", "teensy40-12pad-screen", "sample_data.h")


def read_wav(path):
    with wave.open(path, "r") as w:
        ch, sw, rate, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
        raw = w.readframes(n)
    if sw != 2:
        sys.exit(f"{path}: only 16-bit PCM wavs supported (got {sw*8}-bit)")
    data = struct.unpack(f"<{n*ch}h", raw)
    if ch > 1:  # downmix to mono
        data = [sum(data[i*ch:(i+1)*ch]) // ch for i in range(n)]
    return list(data), rate


def main():
    files = sorted(f for f in os.listdir(SAMPLES) if f.lower().endswith(".wav"))
    if not files:
        sys.exit(f"no .wav files in {SAMPLES}")
    parts = [
        "// AUTO-GENERATED by tools/wav2header.py — DO NOT EDIT.",
        "// Regenerate after changing anything in samples/ (see samples/README.md).",
        "#pragma once", "#include <Arduino.h>", ""]
    total = 0
    for f in files:
        m = re.match(r"(.+)_([\d.]+)\.wav$", f, re.I)
        if not m:
            sys.exit(f"{f}: name must be <name>_<rootHz>.wav, e.g. hang_146.83.wav")
        name, root = m.group(1).upper(), float(m.group(2))
        data, rate = read_wav(os.path.join(SAMPLES, f))
        total += len(data) * 2
        print(f"{f}: {len(data)} samples @ {rate} Hz, root {root} Hz "
              f"({len(data)*2/1024:.0f} KB)")
        parts.append(f"// ── {f} ──")
        parts.append(f"static const uint32_t {name}_LEN = {len(data)}u;")
        parts.append(f"static const float    {name}_ROOT_HZ = {root}f;")
        parts.append(f"static const float    {name}_RATE = {float(rate)}f;")
        parts.append(f"static const int16_t  {name}_SAMPLE[{len(data)}] PROGMEM = {{")
        for i in range(0, len(data), 16):
            parts.append("  " + ",".join(str(v) for v in data[i:i+16]) + ",")
        parts.append("};\n")
    with open(OUT, "w") as fh:
        fh.write("\n".join(parts))
    print(f"wrote {OUT} ({total/1024:.0f} KB of sample data)")


if __name__ == "__main__":
    main()
